https://cwalt2.github.io/portfolio-website/
languageCode = "en-us"
title = "Christopher Walters â€” Portfolio"
# Use minify
enableRobotsTXT = true


[params]
author = "Christopher Walters"
description = "I am pssionate about Cybersecurity, IT, and Software Development. Feel free to look at my projects!"
dateFormat = "Jan 2, 2006"
github = "https://github.com/cwalt2"
linkedin = "https://www.linkedin.com/in/cwalt2"


[outputs]
home = ["HTML", "RSS"]


[permalinks]
projects = "/projects/:slug/"
